Ext.Loader.setConfig({enabled:!0,disableCaching:!1,paths:{GeoExt:"geoext2/src/GeoExt",Ext:"extjs4/src","GeoExt.ux":"geoext_ux"}});OpenLayers.Popup.FramedCloud.prototype.autoSize=!1;AutoSizeFramedCloud=OpenLayers.Class(OpenLayers.Popup.FramedCloud,{autoSize:!0});AutoSizeFramedCloudMinSize=OpenLayers.Class(OpenLayers.Popup.FramedCloud,{autoSize:!0,minSize:new OpenLayers.Size(400,400)});
AutoSizeFramedCloudMaxSize=OpenLayers.Class(OpenLayers.Popup.FramedCloud,{autoSize:!0,maxSize:new OpenLayers.Size(100,100)});
var gcs=new OpenLayers.Projection("EPSG:4326"),merc=new OpenLayers.Projection("EPSG:900913"),utm=new OpenLayers.Projection("EPSG:32647"),indian=new OpenLayers.Projection("EPSG:24047"),map,mapPanel,tree,store,bing_road,bing_hybrid,bing_aerial,overlay,panel_west,ge,styles,create_styles,v_style,v_style_map,sym_lookup,create_layer_vectorLayer,vectorLayer,frm_input_ctrl,frm_input,popup_vectorLayer,create_layer_markers,marker,markers,popup_marker,create_layer_hili,hili,create_layer_pointLayer,pointLayer,
ctrl_popup_pointLayer,popup_pointLayer,del_feat_ctrl,create_layer_kml,kml,select_kml;google.load("earth","1");function info(a,b){Ext.Msg.show({title:a,msg:b,minWidth:200,modal:!0,icon:Ext.Msg.INFO,buttons:Ext.Msg.OK})}
create_styles=function(){styles=new OpenLayers.StyleMap({"default":new OpenLayers.Style(null,{rules:[new OpenLayers.Rule({symbolizer:{Point:{pointRadius:5,graphicName:"square",fillColor:"#EC940C",fillOpacity:.75,strokeWidth:1,strokeOpacity:1,strokeColor:"#3333aa"},Line:{strokeWidth:2,strokeOpacity:1,strokeColor:"#006600"},Polygon:{strokeWidth:2,strokeOpacity:1,fillColor:"#6666aa",strokeColor:"#2222aa"}}})]}),select:new OpenLayers.Style(null,{rules:[new OpenLayers.Rule({symbolizer:{Point:{pointRadius:5,
graphicName:"square",fillColor:"#EC940C",fillOpacity:.25,strokeWidth:2,strokeOpacity:1,strokeColor:"#0000ff"},Line:{strokeWidth:3,strokeOpacity:1,strokeColor:"#0000ff"},Polygon:{strokeWidth:2,strokeOpacity:1,fillColor:"#0000ff",strokeColor:"#0000ff"}}})]}),temporary:new OpenLayers.Style(null,{rules:[new OpenLayers.Rule({symbolizer:{Point:{graphicName:"square",pointRadius:5,fillColor:"#EC940C",fillOpacity:.25,strokeWidth:2,strokeColor:"#0000ff"},Line:{strokeWidth:3,strokeOpacity:1,strokeColor:"#0000ff"},
Polygon:{strokeWidth:2,strokeOpacity:1,strokeColor:"#0000ff",fillColor:"#0000ff"}}})]})})};
create_layer_vectorLayer=function(){function a(a){var c=a.clone();c.geometry.transform(merc,gcs);c=c.geometry.toString();Ext.getCmp("id_location").setValue(c);popup_vectorLayer||(popup_vectorLayer=Ext.create("GeoExt.window.Popup",{title:"DSI Popup",id:"id_popup",location:a,width:604,items:[frm_input],maximizable:!0,collapsible:!0,closeAction:"hide",anchorPosition:"auto"}),popup_vectorLayer.on({close:function(){-1<OpenLayers.Util.indexOf(vectorLayer.selectedFeatures,this.feature)&&frm_input_ctrl.unselect(this.feature)}}));
popup_vectorLayer.show()}vectorLayer=new OpenLayers.Layer.Vector("vectorLayer",{displayInLayerSwitcher:!0,hideIntree:!0,styleMap:styles});vectorLayer.events.on({featureselected:function(b){if(0==Ext.getCmp("id_select_feat").pressed)return!1;a(b.feature)}});frm_input_ctrl=new OpenLayers.Control.SelectFeature(vectorLayer);frm_input=Ext.create("Ext.form.Panel",{title:"Inner Tabs",id:"id_frm_input",url:"rb/process_input.rb",bodyStyle:"padding:5px",width:600,fieldDefaults:{labelAlign:"top",msgTarget:"side"},
defaults:{anchor:"100%"},items:[{layout:"column",border:!1,items:[{columnWidth:.5,border:!1,layout:"anchor",defaultType:"textfield",items:[{fieldLabel:"First Name",name:"first",anchor:"95%"},{fieldLabel:"Company",name:"company",anchor:"95%"}]},{columnWidth:.5,border:!1,layout:"anchor",defaultType:"textfield",items:[{fieldLabel:"Last Name",name:"last",anchor:"95%"},{fieldLabel:"Email",name:"email",vtype:"email",anchor:"95%"}]}]},{xtype:"tabpanel",plain:!0,activeTab:0,height:235,defaults:{bodyStyle:"padding:10px"},
items:[{title:"Demo Input",defaults:{width:200},items:[{xtype:"textfield",fieldLabel:"Title",name:"name",allowBlank:!1,enableKeyEvents:!0,listeners:{keyup:function(){Ext.getCmp("id_upload_title").setValue(this.value)}}},{xtype:"combo",fieldLabel:"Select Layer",id:"id_icon",listConfig:{getInnerTpl:function(){return'<div><img src="img/{icon}.png" align="left" width="16" height="16" >&nbsp;&nbsp;{text}</div>'}},store:new Ext.data.SimpleStore({data:[["icon1","Layer 1"],["icon2","Layer 2"],["x1","Label 1"],
["x2","Label 2"],["x3","Label 3"],["x4","Label 4"],["x5","Label 5"],["x6","Label 6"],["x7","Label 7"],["x8","Label 8"],["x9","Label 9"]],id:0,fields:["icon","text"]}),valueField:"icon",displayField:"text",triggerAction:"all",editable:!1,name:"icon"},{xtype:"textfield",fieldLabel:"Description",name:"description",allowBlank:!1},{xtype:"textareafield",fieldLabel:"Location",name:"location",id:"id_location",width:"100%",anchor:"100%"}]},{xtype:"form",title:"Upload Photo",width:500,frame:!0,title:"Upload photo",
bodyPadding:"10 10 0",defaults:{anchor:"100%",xtype:"textfield",msgTarget:"side",labelWidth:50},items:[{fieldLabel:"Title",id:"id_upload_title",name:"upload_title",disabled:!0},{xtype:"filefield",name:"file",id:"id_file",fieldLabel:"Photo",labelWidth:50,msgTarget:"side",allowBlank:!0,buttonText:"",buttonConfig:{iconCls:"upload"}},{fieldLabel:"File saved",name:"origname",id:"id_origname"},{xtype:"hidden",name:"imgname",id:"id_imgname"}],buttons:[{text:"Upload",handler:function(){var a=this.up("form").getForm();
a.isValid()&&a.submit({url:"rb/file-upload.rb",waitMsg:"Uploading photo...",success:function(a,b){var e=Ext.decode(b.response.responseText),g=e.imgname,e=e.origname;Ext.getCmp("id_imgname").setValue(g);Ext.getCmp("id_origname").setValue(e);info("Success","File "+e+" has been uploaded!")}})}},{text:"Reset",handler:function(){this.up("form").getForm().reset()}}]},{cls:"x-plain",title:"WYSIWYG",layout:"fit",items:{xtype:"htmleditor",name:"wysiwyg",fieldLabel:"WYSIWYG"}}]}],buttons:[{text:"Save",handler:function(){frm_input.getForm().submit({success:function(a,
c){Ext.Msg.show({title:"Info",msg:"1 feature added!",buttons:Ext.Msg.OK,icon:Ext.Msg.INFO,fn:function(a){vectorLayer.removeAllFeatures();frm_input.getForm().reset();popup_vectorLayer.hide();pointLayer&&(map.removeLayer(pointLayer),map.removeControl(ctrl_popup_pointLayer),ctrl_popup_pointLayer=pointLayer=null);create_layer_pointLayer();map.addLayer(pointLayer);frm_input_ctrl.deactivate()}})},failure:function(a,c){Ext.Msg.alert("Error","Failed!!")}})}},{text:"Cancel",handler:function(){var a=Ext.getCmp("id_location"),
c=a.getValue();frm_input.getForm().reset();a.setValue(c)}}]})};
create_layer_pointLayer=function(){function a(a){ctrl_popup_pointLayer.unselectAll()}var b=new OpenLayers.Style({fillColor:"#ffffff",fillOpacity:.8,strokeColor:"#aa0000",strokeWidth:2,pointRadius:3}),b=new OpenLayers.StyleMap({"default":b});b.addUniqueValueRules("default","kmlname",{layer_1:{backgroundGraphic:"img/icon_marker_green.png",backgroundWidth:32,backgroundHeight:32,backgroundYOffset:-32},layer_2:{backgroundGraphic:"img/icon_marker_blue.png",backgroundWidth:32,backgroundHeight:32,backgroundYOffset:-32},
layer_x1:{backgroundGraphic:"img/x1.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},layer_x2:{backgroundGraphic:"img/x2.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},layer_x3:{backgroundGraphic:"img/x3.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},layer_x4:{backgroundGraphic:"img/x4.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},layer_x5:{backgroundGraphic:"img/x5.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},
layer_x6:{backgroundGraphic:"img/x6.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},layer_x7:{backgroundGraphic:"img/x7.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},layer_x8:{backgroundGraphic:"img/x8.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27},layer_x9:{backgroundGraphic:"img/x9.png",backgroundWidth:27,backgroundHeight:27,backgroundYOffset:-27}});pointLayer=new OpenLayers.Layer.Vector("Custom Layer",{projection:gcs,strategies:[new OpenLayers.Strategy.BBOX,
new OpenLayers.Strategy.Refresh],protocol:new OpenLayers.Protocol.WFS({srsName:"EPSG:4326",url:"http://127.0.0.1/cgi-bin/mapserv?map=/ms603/map/wfs-postgis.map&SERVICE=WFS&srsName=EPSG:4326",featureType:"kml",featurePrefix:"feature"}),styleMap:b});ctrl_popup_pointLayer=new OpenLayers.Control.SelectFeature(pointLayer,{hover:!0,toggle:!0,clickOut:!1,multiple:!1,box:!1,eventListeners:{featurehighlighted:function(b){sel_feat=b;new OpenLayers.LonLat(b.feature.geometry.x,b.feature.geometry.y);feature=b.feature;
b=feature.attributes.imgname;var c="./photos/"+feature.attributes.imgname,g=feature.attributes.descr;content="<h2>"+feature.attributes.name+"(id:"+feature.attributes.id+")</h2>";b&&(content+="<img class='imgpopup' src='"+c+"' />");content+=g;popup_pointLayer=new OpenLayers.Popup.FramedCloud("chicken",feature.geometry.getBounds().getCenterLonLat(),new OpenLayers.Size(250,180),content,null,!0,a);feature.popup=popup_pointLayer;popup_pointLayer.calculateRelativePosition=function(){return"tr"};map.addPopup(popup_pointLayer)},
featureunhighlighted:function(a){a=a.feature;a.popup&&(map.removePopup(a.popup),a.popup.destroy(),delete a.popup)}}});map.addControl(ctrl_popup_pointLayer);ctrl_popup_pointLayer.activate();var c=function(a){var b=a.attributes.name;Ext.Ajax.request({url:"rb/kml_delete.rb",params:{id:a.attributes.id},success:function(a,c){info("Result","\u0e25\u0e1a\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23 "+b+" \u0e2d\u0e2d\u0e01\u0e08\u0e32\u0e01\u0e10\u0e32\u0e19\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e40\u0e23\u0e35\u0e22\u0e1a\u0e23\u0e49\u0e2d\u0e22\u0e41\u0e25\u0e49\u0e27")},
failure:function(a,b){Ext.Msg.alert("Warning","\u0e40\u0e01\u0e34\u0e14\u0e02\u0e49\u0e2d\u0e1c\u0e34\u0e14\u0e1e\u0e25\u0e32\u0e14\u0e44\u0e21\u0e48\u0e2a\u0e32\u0e21\u0e32\u0e23\u0e16\u0e25\u0e1a\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e44\u0e14\u0e49")}})};del_feat_ctrl=new OpenLayers.Control.SelectFeature(pointLayer,{clickout:!0,onSelect:function(a){Ext.Msg.confirm("Confirm","\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e25\u0e1a  "+a.attributes.name+
" \u0e2d\u0e2d\u0e01\u0e08\u0e32\u0e01\u0e10\u0e32\u0e19\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25 \u0e43\u0e0a\u0e48\u0e2b\u0e23\u0e37\u0e2d\u0e44\u0e21\u0e48 ?",function(b){"yes"==b&&(pointLayer.removeFeatures(a),c(a))})},toggle:!0,multiple:!1,hover:!1});map.addControl(del_feat_ctrl)};create_layer_markers=function(){markers=new OpenLayers.Layer.Markers("Markers",{displayInLayerSwitcher:!0,hideIntree:!0})};
create_layer_hili=function(){hili=new OpenLayers.Layer.WMS("Hili","http://203.151.201.129/cgi-bin/mapserv",{map:"/ms603/map/hili.map",layers:"hili",transparent:!0},{isBaseLayer:!1,displayInLayerSwitcher:!0,singleTile:!0,ratio:1,hideIntree:!0});hili.setOpacity(0)};
create_layer_kml=function(a){function b(a){select_kml.unselectAll()}kml&&(kml=null);kml=new OpenLayers.Layer.Vector("KML",{projection:map.displayProjection,strategies:[new OpenLayers.Strategy.Fixed],protocol:new OpenLayers.Protocol.HTTP({url:a,format:new OpenLayers.Format.KML({externalProjection:new OpenLayers.Projection("ESPG:4326"),internalProjection:new OpenLayers.Projection("ESPG:900913"),extractStyles:!0,extractAttributes:!0})})});map.addLayer(kml);select_kml=new OpenLayers.Control.SelectFeature(kml);
kml.events.on({featureselected:function(a){a=a.feature;var d="<h2>"+a.attributes.name+"</h2>"+a.attributes.description;-1!=d.search("<script")&&(d="Content contained Javascript! Escaped content below.<br>"+d.replace(/</g,"&lt;"));popupClass=AutoSizeFramedCloud;popup=new OpenLayers.Popup.FramedCloud("chicken",a.geometry.getBounds().getCenterLonLat(),new OpenLayers.Size(100,100),d,null,!0,b);a.popup=popup;map.addPopup(popup)},featureunselected:function(a){a=a.feature;a.popup&&(map.removePopup(a.popup),
a.popup.destroy(),delete a.popup)}});map.addControl(select_kml);select_kml.activate()};function dms2dd(a,b,c){a=parseFloat(a);b=parseFloat(b)/60;c=parseFloat(c)/3600;return a+b+c}function dd2dms(a){var b=parseInt(a/100*100);a=60*(a-b);var c=parseInt(a),d=[];d[0]=b;d[1]=c;d[2]=(60*(a-c)).toFixed(2);return d}
function setMarker(a,b,c){b=(new OpenLayers.LonLat(a,b)).transform(gcs,merc);a=new OpenLayers.Feature(markers,b);a.closeBox=!0;a.popupClass=OpenLayers.Class(OpenLayers.Popup.AnchoredBubble,{maxSize:new OpenLayers.Size(120,75)});a.data.popupContentHTML=c;a.data.overflow="hidden";c=new OpenLayers.Size(64,64);var d=new OpenLayers.Pixel(-(c.w/2),-c.h);c=new OpenLayers.Icon("img/icon_marker.png",c,d);b=new OpenLayers.Marker(b,c);b.feature=a;markers.addMarker(b)}
function addMarkers(){var a;a=new OpenLayers.LonLat(13,100);addMarker(a,AutoSizeFramedCloud,'<div style="background-color:red;">Popup.FramedCloud<br>autosize - wide short text<br>closebox<br>'+samplePopupContentsHTML_WideShort+"</div>",!0)}
function addMarker(a,b,c,d,e){a=new OpenLayers.Feature(markers,a);a.closeBox=d;a.popupClass=b;a.data.popupContentHTML=c;a.data.overflow=e?"auto":"hidden";marker=a.createMarker();marker.events.register("mousedown",a,function(a){null==this.popup?(this.popup=this.create_popup_marker(this.closeBox),map.addPopup(this.popup),this.popup.show()):this.popup.toggle();currentPopup=this.popup;OpenLayers.Event.stop(a)});markers.addMarker(marker)}
function onFeatureSelect(a){selectedFeature=a;popup_marker=new OpenLayers.Popup.FramedCloud("",a.geometry.getBounds().getCenterLonLat(),new OpenLayers.Size(100,100),"<div style='padding:15px 5px 5px 10px;'><table style='font-size:13px;color:red'><tr><td width='40%'>Name</td><td width='5%'>:</td><td>"+a.attributes.label+"</td></tr></table></div>",null,!0,onMarkerPopupClose);a.popup=popup_marker;map.addPopup(popup_marker)}function onMarkerPopupClose(a){frm_input_ctrl.unselectAll()}
function onFeatureUnselect(a){map.removePopup(a.popup);a.popup.destroy();a.popup=null}
var test_gps=function(){Ext.getCmp("londd").setValue(100);Ext.getCmp("lonmm").setValue(33);Ext.getCmp("lonss").setValue(57.9126);Ext.getCmp("latdd").setValue(13);Ext.getCmp("latmm").setValue(53);Ext.getCmp("latss").setValue(26.757)},check_gps=function(){var a=Ext.getCmp("londd").getValue(),b=Ext.getCmp("lonmm").getValue(),c=Ext.getCmp("lonss").getValue(),d=Ext.getCmp("latdd").getValue(),e=Ext.getCmp("latmm").getValue(),g=Ext.getCmp("latss").getValue();report(a,b,c,d,e,g)},report=function(a,b,c,d,
e,g){Ext.Ajax.request({url:"rb/checkLonLat2.rb",params:{method:"GET",lodd:a,lomm:b,loss:c,ladd:d,lamm:e,lass:g,format:"json"},failure:function(a,b){alert("checkLonLat2 > failure");return!1},success:function(a,b){var c=Ext.decode(a.responseText),d=parseFloat(c.lon),e=parseFloat(c.lat),d=(new OpenLayers.LonLat(d,e)).transform(gcs,merc);map.setCenter(d,14);var e=new OpenLayers.Size(48,48),g=new OpenLayers.Pixel(-(e.w/2),-e.h),e=new OpenLayers.Icon("img/icon_marker.png",e,g);markers.addMarker(new OpenLayers.Marker(d,
e));info("Result",c.msg)}})},gps=Ext.create("Ext.form.Panel",{title:"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07\u0e1e\u0e34\u0e01\u0e31\u0e14 GPS (Geographic)",id:"id_gps",frame:!0,items:[{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelSeparator:"",labelAlign:"top",margin:"0 5 0 0"},items:[{xtype:"textfield",id:"londd",fieldLabel:"Lon:DD",width:50},{xtype:"textfield",id:"lonmm",fieldLabel:"Lon:MM",width:50},{xtype:"textfield",id:"lonss",fieldLabel:"Lon:SS",
width:50},{xtype:"displayfield",fieldLabel:"&nbsp;",value:"E"}]},{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelSeparator:"",labelAlign:"top",margin:"0 5 0 0"},items:[{xtype:"textfield",id:"latdd",fieldLabel:"Lat:DD",width:50},{xtype:"textfield",id:"latmm",fieldLabel:"Lat:MM",width:50},{xtype:"textfield",id:"latss",fieldLabel:"Lat:SS",width:50},{xtype:"displayfield",fieldLabel:"&nbsp;",value:"N"}]},{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",
pack:"center"},fieldDefaults:{labelSeparator:"",labelAlign:"top",margin:"0 5 0 0"},items:[{xtype:"button",text:"Check",handler:check_gps,width:80},{xtype:"button",text:"Clear",handler:function(){gps.getForm().reset();markers.clearMarkers()},width:80},{xtype:"button",text:"Test",handler:test_gps,width:80}]}]}),gps_format=0,gps_tip="\u0e23\u0e39\u0e1b\u0e41\u0e1a\u0e1a\u0e04\u0e48\u0e32\u0e1e\u0e34\u0e01\u0e31\u0e14\u0e17\u0e35\u0e48\u0e2a\u0e32\u0e21\u0e32\u0e23\u0e16\u0e40\u0e25\u0e37\u0e2d\u0e01\u0e43\u0e0a\u0e49\u0e44\u0e14\u0e49 <br>",
gps_tip=gps_tip+"100.56578<br>",gps_tip=gps_tip+"100 33 56.808<br>",gps_tip=gps_tip+"100d 33m 56.808s<br>",gps_tip=gps_tip+"100DD 33MM 56.808SS<br>";function dms2dd(a,b,c){a=parseFloat(a);b=parseFloat(b)/60;c=parseFloat(c)/3600;return a+b+c}function dd2dms(a){var b=parseInt(a/100*100);a=60*(a-b);var c=parseInt(a),d=[];d[0]=b;d[1]=c;d[2]=(60*(a-c)).toFixed(2);return d}
function setMarker(a,b,c){b=(new OpenLayers.LonLat(a,b)).transform(gcs,merc);a=new OpenLayers.Feature(markers,b);a.closeBox=!0;a.popupClass=OpenLayers.Class(OpenLayers.Popup.AnchoredBubble,{maxSize:new OpenLayers.Size(120,75)});a.data.popupContentHTML=c;a.data.overflow="hidden";c=new OpenLayers.Size(64,64);var d=new OpenLayers.Pixel(-(c.w/2),-c.h);c=new OpenLayers.Icon("img/icon_marker.png",c,d);b=new OpenLayers.Marker(b,c);b.feature=a;markers.addMarker(b)}
function addMarkers(){var a;a=new OpenLayers.LonLat(13,100);addMarker(a,AutoSizeFramedCloud,'<div style="background-color:red;">Popup.FramedCloud<br>autosize - wide short text<br>closebox<br>'+samplePopupContentsHTML_WideShort+"</div>",!0)}
function addMarker(a,b,c,d,e){a=new OpenLayers.Feature(markers,a);a.closeBox=d;a.popupClass=b;a.data.popupContentHTML=c;a.data.overflow=e?"auto":"hidden";marker=a.createMarker();b=function(a){null==this.popup?(this.popup=this.create_popup_marker(this.closeBox),map.addPopup(this.popup),this.popup.show()):this.popup.toggle();currentPopup=this.popup;OpenLayers.Event.stop(a)};marker.events.register("mousedown",a,b);markers.addMarker(marker)}
function onFeatureSelect(a){selectedFeature=a;popup_marker=new OpenLayers.Popup.FramedCloud("",a.geometry.getBounds().getCenterLonLat(),new OpenLayers.Size(100,100),"<div style='padding:15px 5px 5px 10px;'><table style='font-size:13px;color:red'><tr><td width='40%'>Name</td><td width='5%'>:</td><td>"+a.attributes.label+"</td></tr></table></div>",null,!0,onMarkerPopupClose);a.popup=popup_marker;map.addPopup(popup_marker)}function onMarkerPopupClose(a){frm_input_ctrl.unselectAll()}
function onFeatureUnselect(a){map.removePopup(a.popup);a.popup.destroy();a.popup=null}var test_gps2=function(){var a,b;gps_format+=1;1==gps_format?(a="100.56578",b="13.89072"):2==gps_format?(a="100 33 56.808",b="13 53 26.592"):3==gps_format?(a="100d 33m 56.808s",b="13d 53m 26.592s"):4==gps_format&&(gps_format=0,a="100DD 33MM 56.808SS",b="13DD 53MM 26.592SS");Ext.getCmp("gps_lon").setValue(a);Ext.getCmp("gps_lat").setValue(b)};String.prototype.strip=function(){return this.replace(/^\s+|\s+$/g,"")};
var gps_msg,check_gps2=function(){var a=Ext.getCmp("gps_lon").getValue(),b=Ext.getCmp("gps_lat").getValue(),c,a=a.replace(/\s+/g," ").strip().replace(/[A-Za-z$-]/g,"").split(/\s/g),d=b.replace(/\s+/g," ").strip().replace(/[A-Za-z$-]/g,"").split(/\s/g);if(1==a.length&&1==d.length)b=a[0],c=d[0],gps_msg="\u0e1e\u0e34\u0e01\u0e31\u0e14 "+b+" E "+c+" N<br>";else if(3==a.length&&3==d.length)b=dms2dd(a[0],a[1],a[2]),c=dms2dd(d[0],d[1],d[2]),gps_msg="\u0e1e\u0e34\u0e01\u0e31\u0e14 "+a[0]+"&deg; "+a[1]+"&apos; "+
a[2]+"&quot; E ",gps_msg+=d[0]+"&deg; "+d[1]+"&apos; "+d[2]+"&quot; N<br>";else return alert("\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e17\u0e35\u0e48\u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01\u0e43\u0e19\u0e0a\u0e48\u0e2d\u0e07 Longitude \u0e41\u0e25\u0e30/\u0e2b\u0e23\u0e37\u0e2d  Latitude \u0e44\u0e21\u0e48\u0e16\u0e39\u0e01\u0e15\u0e49\u0e2d\u0e07"),!1;gps_report(b,c)},gps_report=function(a,b){Ext.Ajax.request({url:"rb/checkLonLatDD.rb",params:{method:"GET",lon:a,lat:b,format:"json"},failure:function(a,
b){alert("checkLonLatDD > failure");return!1},success:function(a,b){var e=Ext.decode(a.responseText),g=parseFloat(e.lon),h=parseFloat(e.lat);gps_msg+=e.msg;e=(new OpenLayers.LonLat(g,h)).transform(gcs,merc);map.setCenter(e,14);g=new OpenLayers.Size(48,48);h=new OpenLayers.Pixel(-(g.w/2),-g.h);g=new OpenLayers.Icon("img/icon_marker.png",g,h);markers.addMarker(new OpenLayers.Marker(e,g));info("Result",gps_msg)}})},gps2=Ext.create("Ext.form.Panel",{title:"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07\u0e1e\u0e34\u0e01\u0e31\u0e14 GPS",
id:"id_gps2",frame:!0,items:[{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelSeparator:"",labelAlign:"top",margin:"0 5 0 0"},items:[{xtype:"textfield",id:"gps_lon",fieldLabel:"Longitude",width:150},{xtype:"displayfield",fieldLabel:"&nbsp;",value:"E"}]},{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelSeparator:"",labelAlign:"top",margin:"0 5 0 0"},items:[{xtype:"textfield",id:"gps_lat",fieldLabel:"Latitude",width:150},
{xtype:"displayfield",fieldLabel:"&nbsp;",value:"N"}]},{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelSeparator:"",labelAlign:"top",margin:"0 5 0 0"},items:[{xtype:"button",text:"Check",handler:check_gps2,width:80},{xtype:"button",text:"Clear",handler:function(){gps2.getForm().reset();markers.clearMarkers()},width:80},{xtype:"button",text:"Test",tooltip:gps_tip,handler:test_gps2,width:80}]},{xtype:"panel",border:!1,items:[{html:'<center><font color="green">Click \u0e17\u0e35\u0e48\u0e1b\u0e38\u0e48\u0e21 [Test]<br>\u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e40\u0e1b\u0e25\u0e35\u0e48\u0e22\u0e19\u0e23\u0e39\u0e1b\u0e41\u0e1a\u0e1a\u0e02\u0e2d\u0e07 GPS<br>\u0e17\u0e35\u0e48\u0e2a\u0e32\u0e21\u0e32\u0e23\u0e16\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19\u0e44\u0e14\u0e49</font></center>'}]}]}),
check_gps_utm=function(){var a=Ext.getCmp("utmn").getValue(),b=Ext.getCmp("utme").getValue();zone=1==Ext.getCmp("zone47").checked?"47":"48";report_utm(a,b,zone)},report_utm=function(a,b,c){Ext.Ajax.request({url:"rb/checkUTM.rb",params:{method:"GET",utmn:a,utme:b,zone:c,format:"json"},failure:function(a,b){alert("checkUTM > failure");return!1},success:function(a,b){var c=Ext.decode(a.responseText),h=parseFloat(c.lon),f=parseFloat(c.lat),h=(new OpenLayers.LonLat(h,f)).transform(gcs,merc);map.setCenter(h,
14);var f=new OpenLayers.Size(48,48),k=new OpenLayers.Pixel(-(f.w/2),-f.h),f=new OpenLayers.Icon("img/icon_marker.png",f,k);markers.addMarker(new OpenLayers.Marker(h,f));info("Result",c.msg)}})},test_gps_utm=function(){Ext.getCmp("zone47").checked?(Ext.getCmp("utmn").setValue(1536195.1807),Ext.getCmp("utme").setValue(669189.2284)):(Ext.getCmp("utmn").setValue(1540101.0761),Ext.getCmp("utme").setValue(20494.2993))},gps_utm=Ext.create("Ext.form.Panel",{id:"id_gps_utm",frame:!0,title:"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07\u0e1e\u0e34\u0e01\u0e31\u0e14 GPS (UTM WGS 1984)",
items:[{xtype:"fieldcontainer",hideLabel:!0,layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelAlign:"top",margin:"0 5 0 0",labelWidth:90,labelSeparator:""},items:[{xtype:"textfield",fieldLabel:"Easting:Meters",id:"utme"},{xtype:"displayfield",fieldLabel:"&nbsp;",value:"E"}]},{xtype:"fieldcontainer",hideLabel:!0,layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelAlign:"top",margin:"0 5 0 0",labelWidth:90,labelSeparator:""},items:[{xtype:"textfield",fieldLabel:"Northing:Meters",
id:"utmn"},{xtype:"displayfield",fieldLabel:"&nbsp;",value:"N"}]},{xtype:"fieldcontainer",hideLabel:!0,layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelAlign:"top",margin:"0 40 0 0",labelWidth:90,labelSeparator:""},items:[{xtype:"radio",id:"zone47",name:"zone",fieldLabel:"Zone 47",checked:!0},{xtype:"radio",id:"zone48",name:"zone",fieldLabel:"Zone 48"}]},{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelSeparator:"",labelAlign:"top",margin:"0 5 0 0"},
items:[{xtype:"button",text:"Check",handler:check_gps_utm,width:80},{xtype:"button",text:"Clear",handler:function(){gps_utm.getForm().reset();markers.clearMarkers()},width:80},{xtype:"button",text:"Test",handler:test_gps_utm,width:80}]}]}),check_gps_utm=function(){var a=Ext.getCmp("utmn").getValue(),b=Ext.getCmp("utme").getValue();zone=1==Ext.getCmp("zone47").checked?"47":"48";report_utm(a,b,zone)},report_utm=function(a,b,c){Ext.Ajax.request({url:"rb/checkUTM.rb",params:{method:"GET",utmn:a,utme:b,
zone:c,format:"json"},failure:function(a,b){alert("checkUTM > failure");return!1},success:function(a,b){var c=Ext.decode(a.responseText),h=parseFloat(c.lon),f=parseFloat(c.lat),h=(new OpenLayers.LonLat(h,f)).transform(gcs,merc);map.setCenter(h,14);var f=new OpenLayers.Size(48,48),k=new OpenLayers.Pixel(-(f.w/2),-f.h),f=new OpenLayers.Icon("img/icon_marker.png",f,k);markers.addMarker(new OpenLayers.Marker(h,f));info("Result",c.msg)}})},check_gps_utm_indian=function(){var a=Ext.getCmp("utmni").getValue(),
b=Ext.getCmp("utmei").getValue();zonei=1==Ext.getCmp("zone47i").checked?"47":"48";report_utm_indian(a,b,zonei)},report_utm_indian=function(a,b,c){Ext.Ajax.request({url:"rb/checkUTMIndian.rb",params:{method:"GET",utmn:a,utme:b,zone:c,format:"json"},failure:function(a,b){alert("checkUTMIndian > failure");return!1},success:function(a,b){var c=Ext.decode(a.responseText),h=parseFloat(c.lon),f=parseFloat(c.lat),h=(new OpenLayers.LonLat(h,f)).transform(gcs,merc);map.setCenter(h,14);var f=new OpenLayers.Size(48,
48),k=new OpenLayers.Pixel(-(f.w/2),-f.h),f=new OpenLayers.Icon("img/icon_marker.png",f,k);markers.addMarker(new OpenLayers.Marker(h,f));info("Result",c.msg)}})},test_gps_utm_indian=function(){Ext.getCmp("zone47i").checked?(Ext.getCmp("utmni").setValue(1535891.7973),Ext.getCmp("utmei").setValue(669523.2828)):(Ext.getCmp("utmni").setValue(1539787.7522),Ext.getCmp("utmei").setValue(20913.1788))},gps_utm_indian=Ext.create("Ext.form.Panel",{id:"id_gps_utm_indian",frame:!0,title:"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07\u0e1e\u0e34\u0e01\u0e31\u0e14 GPS (UTM Indian 1975)",
bodyStyle:"padding:5px 5px 5px",items:[{xtype:"fieldcontainer",hideLabel:!0,layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelAlign:"top",margin:"0 5 0 0",labelWidth:90,labelSeparator:""},items:[{xtype:"textfield",fieldLabel:"Easting:Meters",id:"utmei"},{xtype:"displayfield",fieldLabel:"&nbsp;",value:"E"}]},{xtype:"fieldcontainer",hideLabel:!0,layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelAlign:"top",margin:"0 5 0 0",labelWidth:90,labelSeparator:""},items:[{xtype:"textfield",
fieldLabel:"Easting:Meters",id:"utmni"},{xtype:"displayfield",fieldLabel:"&nbsp;",value:"N"}]},{xtype:"fieldcontainer",hideLabel:!0,layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelAlign:"top",margin:"0 40 0 0",labelWidth:90,labelSeparator:""},items:[{xtype:"radio",id:"zone47i",name:"zonei",fieldLabel:"Zone 47",checked:!0},{xtype:"radio",id:"zone48i",name:"zonei",fieldLabel:"Zone 48"}]},{xtype:"fieldcontainer",layout:{type:"hbox",padding:"5",pack:"center"},fieldDefaults:{labelSeparator:"",
labelAlign:"top",margin:"0 5 0 0"},items:[{xtype:"button",text:"Check",handler:check_gps_utm_indian,width:80},{xtype:"button",text:"Clear",handler:function(){gps_utm_indian.getForm().reset();markers.clearMarkers()},width:80},{xtype:"button",text:"Test",handler:test_gps_utm_indian,width:80}]}]}),search_query=function(){var a=Ext.getCmp("id_query").getValue();search(a)},search=function(a){Ext.Ajax.request({url:"rb/search-googlex.rb",params:{method:"GET",query:a,exact:1},success:function(a,c){var d=
Ext.decode(a.responseText),e=d.records[0].loc_text,g=parseFloat(d.records[0].lon).toFixed(2),d=parseFloat(d.records[0].lat).toFixed(2),h=14,f=(new OpenLayers.LonLat(g,d)).transform(gcs,merc);e&&(map.setLayerIndex(markers,0),map.setLayerIndex(hili,0),0==e.indexOf("\u0e08.")?(map.setLayerIndex(hili,99),h=8):0==e.indexOf("\u0e2d.")?(map.setLayerIndex(hili,99),h=10):0==e.indexOf("\u0e15.")?(map.setLayerIndex(hili,99),h=12):(h=14,map.setLayerIndex(markers,99),setMarker(g,d,e)));map.setCenter(f,h);info("Result",
e+"<br>lat:"+d+" lon:"+g);0!=e.search(/\u0e08./)&&0!=e.search(/\u0e2d./)&&0!=e.search(/\u0e15./)&&0!=e.search(/\u0e1a\u0e49\u0e32\u0e19/)||hili.setOpacity(.5)}})};function addWKT(a,b){OpenLayers.loadURL("rb/getPolygonWKT.rb?table="+a+"&gid="+b,"",this,function(a){geom=a.responseText;addWKTFeatures(geom)})}
function addWKTFeatures(a){wkt=new OpenLayers.Format.WKT;features=wkt.read(a);var b;if(features)for(features.constructor!=Array&&(features=[features]),a=0;a<features.length;++a)b?b.extend(features[a].geometry.getBounds().transform(gcs,merc)):(b=features[a].geometry.getBounds(),b=b.transform(gcs,merc));vectorLayer.removeAllFeatures();vectorLayer.addFeatures(features[0].geometry.transform(gcs,merc));map.zoomToExtent(b)}
var myTextField=Ext.create("GeoExt.ux.QryComboBox",{id:"id_query",fieldLabel:"\u0e04\u0e49\u0e19\u0e2b\u0e32",labelSeparator:":",labelWidth:50,fieldStore:["loc_table","loc_gid","loc_text"],hiddenField:["loc_table","loc_gid"],displayField:"loc_text",urlStore:"rb/search-googlex.rb",width:"110",minListWidth:"300",anchor:"95%"});myTextField.on({select:{fn:function(){Ext.getCmp("btn_search").enable()},scope:this}});myTextField.on("specialkey",specialKey,this);
function specialKey(a,b){b.getKey()!=b.RETURN&&b.getKey()!=b.ENTER||search_query()}
var searchquery=Ext.create("Ext.form.Panel",{id:"id_searchquery",labelAlign:"left",align:"center",frame:!0,title:"\u0e04\u0e49\u0e19\u0e2b\u0e32\u0e2a\u0e16\u0e32\u0e19\u0e17\u0e35\u0e48",bodyStyle:"padding:5px 5px 5px",width:300,items:[{layout:"form",labelWidth:30,items:[myTextField],bodyCfg:{tag:"center"},frame:!0,buttons:[{text:"Search",id:"btn_search",handler:search_query,disabled:!0},{text:"Clear",handler:function(){searchquery.getForm().reset();markers.clearMarkers();hili.setOpacity(0);Ext.getCmp("id_query").focus();
Ext.getCmp("btn_search").disable()}}]}]}),loadxls=Ext.create("Ext.form.Panel",{id:"id_loadxls",title:"Upoad XLS (with Geom)",width:500,frame:!0,title:"Upload XLS",bodyPadding:"10 10 0",defaults:{anchor:"100%",xtype:"textfield",msgTarget:"side",labelWidth:50},items:[{xtype:"filefield",name:"file",id:"id_file_xls",fieldLabel:"XLS",labelWidth:50,msgTarget:"side",allowBlank:!0,buttonText:"",buttonConfig:{iconCls:"upload"}}],buttons:[{text:"Upload",handler:function(){var a=this.up("form").getForm();a.isValid()&&
a.submit({url:"rb/file-upload-xls.rb",waitMsg:"Uploading XLS...",success:function(a,c){var d=Ext.decode(c.response.responseText).kmlname;create_layer_kml(d)}})}},{text:"Reset",handler:function(){this.up("form").getForm().reset()}}]});function numberWithCommas(a){a=a.toString();for(var b=/(-?\d+)(\d{3})/;b.test(a);)a=a.replace(b,"$1,$2");return a}
var check_forest_info=function(a,b){lon=b.lon;lat=b.lat;"\u0e40\u0e02\u0e15\u0e2d\u0e38\u0e17\u0e22\u0e32\u0e19\u0e41\u0e2b\u0e48\u0e07\u0e0a\u0e32\u0e15\u0e34"==a?a="national_park":"\u0e40\u0e02\u0e15\u0e1b\u0e48\u0e32\u0e2a\u0e07\u0e27\u0e19"==a?a="reserve_forest":"\u0e1b\u0e48\u0e32\u0e0a\u0e32\u0e22\u0e40\u0e25\u0e19 \u0e1b\u0e35 2530"==a?a="mangrove_2530":"\u0e1b\u0e48\u0e32\u0e0a\u0e32\u0e22\u0e40\u0e25\u0e19 \u0e1b\u0e35 2543"==a?a="mangrove_2543":"\u0e1b\u0e48\u0e32\u0e0a\u0e32\u0e22\u0e40\u0e25\u0e19 \u0e1b\u0e35 2552"==
a&&(a="mangrove_2552");Ext.Ajax.request({url:"rb/check_forest_info.rb",params:{method:"GET",layer:a,lon:lon,lat:lat,format:"json"},success:function(a,b){var e=Ext.decode(a.responseText),g=e.msg;(new OpenLayers.LonLat(e.lon,e.lat)).transform(gcs,merc);"NA"!=g&&info("Result",g)},failure:function(a,b){alert("check forest info > failure");return!1}})};
